/* eslint-disable react/no-unescaped-entities */
import Head from "next/head";
import Herosection from "../components/Herosection";

export default function Home() {
  return (
    <div>
      <Head>
        <title>News2day</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="">
          <Herosection/>
        </div>
      </main>
    </div>
  );
}
